name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "immaxcheng@foxmail.com"
          git config --global user.name "MaxCheng"
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo deploy

        name: Deploy to Github Pages
        env:
          GIT_NAME: MaxCheng
          GIT_EMAIL: immaxcheng@foxmail.com
          REPO: git@github.com:MaxCDon/blog.git
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ./public && git init && git add .
          git config --global user.name $GIT_NAME
          git config --global user.email $GIT_EMAIL
          git commit -m "Site deployed by GitHub Actions"
          git push --force --quiet "https://$GH_TOKEN@$REPO" gh-pages:gh-pages